---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
setwd("F:/Online Courses/Reproducible Research/Porject 1/repdata_2Fdata%2Factivity")
data<-read.csv("activity.csv")

# 1 - Calculate the total number of steps taken per day
## What is mean total number of steps taken per day?
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 
mean(sum_steps$x)

# 2 - If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day
#histogram
hist(sum_steps$x,breaks=seq(from=0, to=25000, by=2500),col="yellow", xlab="Total number of steps", ylim=c(0, 20),main="Histogram of the total number of steps taken each day(NA removed)")
      

# 3- Calculate and report the mean and median of the total number of steps taken per day
mean(sum_steps$x)
median(sum_steps$x)

## What is the average daily activity pattern?
# 1- Make a time series plot (i.e. \color{red}{\verb|type = "l"|}type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
avg_steps<-aggregate(data$steps,by=list(data$interval),FUN=mean,na.rm=TRUE)

colnames(avg_steps)<-c("interval","steps")

library(ggplot2)

ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()

# 2 - Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
avg_steps[avg_steps$steps==max(avg_steps$steps),1]


## Imputing missing values

# 1 - Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with \color{red}{\verb|NA|}NAs)
sum(is.na(data$steps))
data$steps[is.na(data$steps)]<-mean(data$steps,na.rm=TRUE)
head(data)

#histogram
  
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 

hist(sum_steps$x, 
      breaks=seq(from=0, to=25000, by=2500),
      col="yellow", 
      xlab="Total number of steps", 
      ylim=c(0, 30), 
      main="Total number of steps taken each day\n(NA replaced by mean)")


## Are there differences in activity patterns between weekdays and weekends?
# Convert date into weekdays

data$days=tolower(weekdays(data$date))

#Now categorised days into weekend and weekdays

data$day_type<-ifelse(data$days=="saturday"|data$days=="sunday","weekend","weekday")

#Take mean steps taken on weekend or weekday in the intervals

avg_steps<-aggregate(data$steps,by=list(data$interval,data$day_type),FUN=mean,na.rm=TRUE)

colnames(avg_steps)<-c("interval","day_type","steps")

# Create panel plot between average steps and interval seperated by day type

ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()+facet_wrap(~avg_steps$day_type)
